#!/usr/bin/env bash
# This scrpt read the contents of /etc/passwd
while read -r line; do
	USERNAME=$( echo "$line" | cut -d : -f1 )
	GROUP_ID=$( echo "$line" | cut -d : -f4 )
	HOME=$( echo "$line" | cut -d : -f6 )
	INFO=$( echo "$line" | cut -d : -f5 )
	SHELL=$( echo "$line" | cut -d : -f7 )
	PASSWORD=$( echo "$line" | cut -d : -f2 )
	ID=$( echo "$line" | cut -d : -f3 )
	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME and rides $SHELL. $ID's place is protected by the passcode $PASSWORD, more info about the user here: $INFO"
done < /etc/passwd
