#!/usr/bin/env bash
# Bash script to modify hosts file
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i 's/157.240.11.35/8.8.8.8/' ~/hosts.new
cat ~/hosts.new > /etc/hosts
